# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: picklerixs

channels:
  - conda-forge

dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - xarray
  - pandas
  - ipykernel
